export enum ExecutionStatus {
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum StepStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  COMPENSATED = 'COMPENSATED',
}

export enum StepType {
  BROWSER_NAVIGATE = 'BROWSER_NAVIGATE',
  BROWSER_CLICK = 'BROWSER_CLICK',
  BROWSER_TYPE = 'BROWSER_TYPE',
  BROWSER_EXTRACT = 'BROWSER_EXTRACT',
  API_CALL = 'API_CALL',
  FILE_PROCESS = 'FILE_PROCESS',
}