export enum StepType {
  BROWSER_NAVIGATE = 'BROWSER_NAVIGATE',
  BROWSER_CLICK = 'BROWSER_CLICK',
  BROWSER_TYPE = 'BROWSER_TYPE',
  BROWSER_EXTRACT = 'BROWSER_EXTRACT',
  API_CALL = 'API_CALL',
  FILE_PROCESS = 'FILE_PROCESS',
}