import { CognitiveOutcome } from '../shared/interfaces/agent.interfaces';

export interface ExecutionEventMap {
  'session:started': { sessionId: string; profile: string };
  'plan:created': { plan: any };
  'plan:replanned': { fromStep: number; newStepCount: number };
  'step:started': { stepIndex: number; description: string };
  'step:completed': { stepIndex: number; duration: number; validation?: boolean; confidence: number };
  'step:failed': { stepIndex: number; error?: string };
  'step:blocked': { stepIndex: number; reason?: string };
  'step:denied': { stepIndex: number };
  'step:validation_failed': { stepIndex: number; description: string; confidence: number };
  'execution:event': { type: string; data: Record<string, unknown>; timestamp?: number };
  'execution:completed': { status: 'success' | 'failed'; reason?: string | null; cognitiveOutcome?: CognitiveOutcome; verification?: any };
  'execution:failed': { reason: string; message: string; blockedSteps?: any[]; cognitiveOutcome?: CognitiveOutcome };
  'execution:cancelled': { reason?: string };
  'execution:paused': { reason?: string; message?: string; systemConfidence?: number };
  'execution:resumed': Record<string, never>;
  'execution:verified': { verified: boolean; confidence: number; score: number; summary: string; gaps: string[]; achievements: string[]; nextAction: string; reasoning: string; evidence: any };
  'execution:graph': { sessionId: string; graph: any; domain: string; matchedSkills: string[]; agentId: string | null };
  'execution:state': { sessionId: string; state: string; browserState: string; gateState: string };
  'automation:gate': { sessionId: string; proceed: boolean; requiresApproval: boolean; riskLevel: string; reason: string; targetDomains: string[]; triggers: any };
  'browser:initialized': Record<string, never>;
  'browser:state': { sessionId: string; state: string };
  'approval:requested': { approvalRequestId: string; stepIndex: number; gate?: boolean; riskLevel: string; reason?: string; targetDomains?: string[]; actionDetails: any; expiresAt: Date };
  'approval:responded': { approvalRequestId: string; status: 'APPROVED' | 'DENIED' | 'REJECTED' };
  'approval:expired': { approvalRequestId: string };
  'cos:drift': { stepIndex: number; similarity: number; isDrifted: boolean; type: string | null; phase: string; explanation: string };
  'cos:drift_abort': { stepIndex: number; reason: string; similarity: number };
  'cos:cpn_gate': { stepIndex: number; decision: string; systemConfidence: number; profile: string; reasoning: string; weakestNode: { source: string; confidence: number } | null; thresholds: { abort: number; pause: number; warn: number }; timestamp: number };
  'cos:world_state': { stateConfidence: number; beliefSourceConsensus: number; version: number; belief: Record<string, { value: unknown; confidence: number; source: string }> };
  'cos:world_state_final': { stateConfidence: number; beliefSourceConsensus: number; version: number; historyLength: number };
  'memory:preferences_updated': { sessionId: string; preferences: any; learnedFrom: string[] };
  'memory:preferences_applied': { sessionId: string; domain: string; preferences: any; activeForDomain: string[]; message: string };
  'shadow:report': { report: any };
  'screenshot:frame': { sessionId: string; stepIndex: number; timestamp: number; base64: string; width: number; height: number; url?: string; cursorPosition?: { x: number; y: number } };
  'clarification:required': { sessionId: string; ambiguityScore: number; clarifyingQuestions: string[]; parsedGoal: any };
  'clarification:resolved': { sessionId: string; refinedGoal: any; message: string };
  'agent:domain_routed': { sessionId: string; domain: string; taskType: string };
  'agent:registry_routed': { sessionId: string; agentId: string | null; domain: string; plugins: string[]; parallel: boolean };
  'supervisor:question': { question: string; sessionId: string; timestamp: number };
  'orchestration:building': { planId: string; sessionId: string; timestamp: number; data: { message: string } };
  'orchestration:started': { planId: string; sessionId: string; timestamp: number; data: { message: string } };
  'orchestration:ready': { planId: string; sessionId: string; timestamp: number; data: { message: string; subGoals: any[]; parallelGroups: string[][]; reasoning: string } };
  'orchestration:group_start': { planId: string; sessionId: string; timestamp: number; data: { message: string; group: any[] } };
  'orchestration:group_complete': { planId: string; sessionId: string; timestamp: number; data: { message: string; results: any[] } };
  'orchestration:complete': { planId: string; sessionId: string; timestamp: number; data: { message: string; status: string; result: any; subGoals: any[] } };
  'orchestration:error': { planId: string; sessionId: string; timestamp: number; data: { message: string } };
  'orchestration:cancelled': { planId: string; sessionId: string; timestamp: number; data: { message: string } };
  'subgoal:started': { planId: string; sessionId: string; timestamp: number; data: { subGoalId: string; description: string; agentType: string } };
  'subgoal:delegated': { planId: string; sessionId: string; timestamp: number; data: { subGoalId: string; agentId: string; agentName: string } };
  'subgoal:retrying': { planId: string; sessionId: string; timestamp: number; data: { subGoalId: string; attempt: number; maxRetries: number; error: string } };
  'subgoal:requeued': { planId: string; sessionId: string; timestamp: number; data: { subGoalId: string; retryCount: number; maxRetries: number } };
  'subgoal:completed': { planId: string; sessionId: string; timestamp: number; data: { subGoalId: string; success: boolean; error?: string } };
  'subgoal:failed': { planId: string; sessionId: string; timestamp: number; data: { subGoalId: string; error: string } };
}
